# Generated by Django 5.1.2 on 2024-11-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='customer_images/')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=70)),
            ],
        ),
    ]
