# Generated by Django 5.1.2 on 2024-12-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
