# Generated by Django 5.1.2 on 2024-12-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='desc',
            field=models.CharField(max_length=60),
        ),
    ]
